import type { Metadata } from 'next'
import { Inter, Long_Cang } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })
const long_cang = Long_Cang({ weight: "400", subsets: ['latin'] })
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
